funnel = ''
funnel_prefix = ''

ad_live_opt_in_url = 'https://staging.zonia.com/unbroken'
ad_live_join_zonia_url = 'https://staging.zonia.com/ad-join-zonia'
ad_live_sign_up_url = 'https://staging.zonia.com/ad-signup'
ad_booster_monthly_upsale_url = 'https://staging.zonia.com/ad-booster-packages-monthly'
ad_booster_quarterly_upsale_url = 'https://staging.zonia.com/ad-booster-packages-quarterly'
ad_booster_annually_upsale_url = 'https://staging.zonia.com/ad-booster-packages-annually'
ad_silver_masterclass_url = 'https://staging.zonia.com/ad-mini-masterclass-series-silver-package'
ad_platinum_masterclass_url = 'https://staging.zonia.com/ad-mini-masterclass-series-platinum-package'
ad_masterclass_url = 'https://staging.zonia.com/ad-mini-masterclass-series'
ad_restore_detox_bought_url = 'https://staging.zonia.com/ad-restore-detox-special-immunity-code'
ad_restore_detox_not_bought_url = 'https://staging.zonia.com/ad-restore-detox-special'
ad_restore_detox_upsell_url = 'https://staging.zonia.com/ad-rd-6-more-bottles'
ad_restore_detox_downsell_url = 'https://staging.zonia.com/ad-rd-6-discounted-bottles'
ad_restore_life_url = 'https://staging.zonia.com/ad-restore-life-special'
ad_restore_life_upsell_url = 'https://staging.zonia.com/ad-rl-6-more-bottles'
ad_restore_life_downsell_url = 'https://staging.zonia.com/ad-rl-6-discounted-bottles'
welcome_page_url = 'https://staging.zonia.com/welcome'
user_page_url = 'https://staging.zonia.com/user'

ad_ev_opt_in_url = 'https://staging.zonia.com/admb5e/unbroken'
ad_ev_detox_opt_in_url = 'https://staging.zonia.com/admb5e/ad-detox'
ad_ev_gut_opt_in_url = 'https://staging.zonia.com/admb5e/ad-gut-health'
ad_ev_brain_opt_in_url = 'https://staging.zonia.com/admb5e/ad-brain-health'
ad_ev_mindset_opt_in_url = 'https://staging.zonia.com/admb5e/ad-mindset'
ad_ev_inflammation_opt_in_url = 'https://staging.zonia.com/admb5e/ad-inflammation'
ad_ev_energy_opt_in_url = 'https://staging.zonia.com/admb5e/ad-energy'
ad_ev_pain_opt_in_url = 'https://staging.zonia.com/admb5e/ad-pain-relief'
ad_ev_join_zonia_url = 'https://staging.zonia.com/admb5e/ad-join-zonia'
ad_ev_sign_up_url = 'https://staging.zonia.com/admb5e/ad-signup'

lg_live_opt_in_url = 'https://staging.zonia.com/ageless'
lg_live_metabolism_opt_in_url = 'https://staging.zonia.com/lg-metabolism'
lg_live_skin_opt_in_url = 'https://staging.zonia.com/lg-skin-health'
lg_live_exercise_opt_in_url = 'https://staging.zonia.com/lg-exercise'
lg_live_brain_opt_in_url = 'https://staging.zonia.com/lg-brain-health'
lg_live_hormones_opt_in_url = 'https://staging.zonia.com/lg-hormones'
lg_live_energy_opt_in_url = 'https://staging.zonia.com/lg-energy'
lg_live_inflammation_opt_in_url = 'https://staging.zonia.com/lg-inflammation'
lg_live_bones_opt_in_url = 'https://staging.zonia.com/lg-bones-muscles'
lg_live_join_zonia_url = 'https://staging.zonia.com/lg-join-zonia'
lg_live_sign_up_url = 'https://staging.zonia.com/lg-signup'
lg_booster_monthly_upsale_url = 'https://staging.zonia.com/lg-booster-packages-monthly'
lg_booster_quarterly_upsale_url = 'https://staging.zonia.com/lg-booster-packages-quarterly'
lg_booster_annually_upsale_url = 'https://staging.zonia.com/lg-booster-packages-annually'
lg_silver_masterclass_url = 'https://staging.zonia.com/lg-mini-masterclass-series-silver-package'
lg_platinum_masterclass_url = 'https://staging.zonia.com/lg-mini-masterclass-series-platinum-package'
lg_masterclass_url = 'https://staging.zonia.com/lg-mini-masterclass-series'
lg_restore_life_bought_url = 'https://staging.zonia.com/lg-restore-life-special-longevity-code'
lg_restore_life_not_bought_url = 'https://staging.zonia.com/lg-restore-life-special'
lg_restore_life_upsell_url = 'https://staging.zonia.com/lg-rl-6-more-bottles'
lg_restore_life_downsell_url = 'https://staging.zonia.com/lg-rl-6-discounted-bottles'
lg_restore_detox_url = 'https://staging.zonia.com/lg-restore-detox-special'
lg_restore_detox_upsell_url = 'https://staging.zonia.com/lg-rd-6-more-bottles'
lg_restore_detox_downsell_url = 'https://staging.zonia.com/lg-rd-6-discounted-bottles'

lg_ev_opt_in_url = 'https://staging.zonia.com/lgmb5e/ageless'
lg_ev_metabolism_opt_in_url = 'https://staging.zonia.com/lgmb5e/lg-metabolism'
lg_ev_skin_opt_in_url = 'https://staging.zonia.com/lgmb5e/lg-skin-health'
lg_ev_exercise_opt_in_url = 'https://staging.zonia.com/lgmb5e/lg-exercise'
lg_ev_brain_opt_in_url = 'https://staging.zonia.com/lgmb5e/lg-brain-health'
lg_ev_hormones_opt_in_url = 'https://staging.zonia.com/lgmb5e/lg-hormones'
lg_ev_energy_opt_in_url = 'https://staging.zonia.com/lgmb5e/lg-energy'
lg_ev_inflammation_opt_in_url = 'https://staging.zonia.com/lgmb5e/lg-inflammation'
lg_ev_bones_opt_in_url = 'https://staging.zonia.com/lgmb5e/lg-bones-muscles'
lg_ev_join_zonia_url = 'https://staging.zonia.com/lgmb5e/lg-join-zonia'
lg_ev_sign_up_url = 'https://staging.zonia.com/lgmb5e/lg-signup'

bb_live_opt_in_url = 'https://staging.zonia.com/beyond-the-brain'
bb_live_detox_opt_in_url = 'https://staging.zonia.com/bb-detox'
bb_live_gut_opt_in_url = 'https://staging.zonia.com/bb-gut-health'
bb_live_memory_opt_in_url = 'https://staging.zonia.com/bb-memory'
bb_live_mood_opt_in_url = 'https://staging.zonia.com/bb-mood'
bb_live_sleep_opt_in_url = 'https://staging.zonia.com/bb-sleep'
bb_live_energy_opt_in_url = 'https://staging.zonia.com/bb-energy'
bb_live_immunity_opt_in_url = 'https://staging.zonia.com/bb-immunity'
bb_live_docuseries_4_opt_in_url = 'https://staging.zonia.com/docuseries-4'
bb_live_join_zonia_url = 'https://staging.zonia.com/bb-join-zonia'
bb_live_sign_up_url = 'https://staging.zonia.com/bb-signup'
bb_booster_monthly_upsale_url = 'https://staging.zonia.com/bb-booster-packages-monthly'
bb_booster_quarterly_upsale_url = 'https://staging.zonia.com/bb-booster-packages-quarterly'
bb_booster_annually_upsale_url = 'https://staging.zonia.com/bb-booster-packages-annually'
bb_silver_masterclass_url = 'https://staging.zonia.com/bb-mini-masterclass-series-silver-package'
bb_platinum_masterclass_url = 'https://staging.zonia.com/bb-mini-masterclass-series-platinum-package'
bb_masterclass_url = 'https://staging.zonia.com/bb-mini-masterclass-series'
bb_restore_detox_bought_url = 'https://staging.zonia.com/bb-restore-detox-special-gut-brain-reset'
bb_restore_detox_not_bought_url = 'https://staging.zonia.com/bb-restore-detox-special'
bb_restore_detox_upsell_url = 'https://staging.zonia.com/bb-rd-6-more-bottles'
bb_restore_detox_downsell_url = 'https://staging.zonia.com/bb-rd-6-discounted-bottles'
bb_restore_life_url = 'https://staging.zonia.com/bb-restore-life-special'
bb_restore_life_upsell_url = 'https://staging.zonia.com/bb-rl-6-more-bottles'
bb_restore_life_downsell_url = 'https://staging.zonia.com/bb-rl-6-discounted-bottles'

bb_ev_opt_in_url = 'https://staging.zonia.com/bbmb5e/beyond-the-brain'
bb_ev_detox_opt_in_url = 'https://staging.zonia.com/bbmb5e/bb-detox'
bb_ev_gut_opt_in_url = 'https://staging.zonia.com/bbmb5e/bb-gut-health'
bb_ev_memory_opt_in_url = 'https://staging.zonia.com/bbmb5e/bb-memory'
bb_ev_mood_opt_in_url = 'https://staging.zonia.com/bbmb5e/bb-mood'
bb_ev_sleep_opt_in_url = 'https://staging.zonia.com/bbmb5e/bb-sleep'
bb_ev_energy_opt_in_url = 'https://staging.zonia.com/bbmb5e/bb-energy'
bb_ev_immunity_opt_in_url = 'https://staging.zonia.com/bbmb5e/bb-immunity'
bb_ev_join_zonia_url = 'https://staging.zonia.com/bbmb5e/bb-join-zonia'
bb_ev_sign_up_url = 'https://staging.zonia.com/bbmb5e/bb-signup'

km_live_opt_in_url = 'https://staging.zonia.com/young-and-thriving'
km_live_toxins_opt_in_url = 'https://staging.zonia.com/km-toxins'
km_live_sleep_opt_in_url = 'https://staging.zonia.com/km-sleep'
km_live_gut_opt_in_url = 'https://staging.zonia.com/km-inflammation'
km_live_adhd_opt_in_url = 'https://staging.zonia.com/km-focus'
km_live_mystery_opt_in_url = 'https://staging.zonia.com/km-mystery'
km_live_mood_opt_in_url = 'https://staging.zonia.com/km-mood'
km_live_autism_opt_in_url = 'https://staging.zonia.com/km-neurodevelopment'
km_live_join_zonia_url = 'https://staging.zonia.com/km-join-zonia'
km_live_sign_up_url = 'https://staging.zonia.com/km-signup'
km_booster_monthly_upsale_url = 'https://staging.zonia.com/km-booster-packages-monthly'
km_booster_quarterly_upsale_url = 'https://staging.zonia.com/km-booster-packages-quarterly'
km_booster_annually_upsale_url = 'https://staging.zonia.com/km-booster-packages-annually'
km_booster_lifetime_upsale_url = 'https://staging.zonia.com/km-booster-packages-lifetime'
km_silver_masterclass_url = 'https://staging.zonia.com/km-mini-masterclass-series-silver-package'
km_platinum_masterclass_url = 'https://staging.zonia.com/km-mini-masterclass-series-platinum-package'
km_masterclass_url = 'https://staging.zonia.com/km-mini-masterclass-series'
km_restore_sleep_bought_url = 'https://staging.zonia.com/km-restore-sleep-special-resilience-code'
km_restore_sleep_not_bought_url = 'https://staging.zonia.com/km-restore-sleep-special'
km_restore_sleep_upsell_url = 'https://staging.zonia.com/km-rs-6-more-bottles'
km_restore_sleep_downsell_url = 'https://staging.zonia.com/km-rs-6-discounted-bottles'
km_restore_detox_url = 'https://staging.zonia.com/km-restore-detox-special'
km_restore_detox_upsell_url = 'https://staging.zonia.com/km-rd-6-more-bottles'
km_restore_detox_downsell_url = 'https://staging.zonia.com/km-rd-6-discounted-bottles'

restore_sleep_start_url = 'https://staging.zonia.com/restore-sleep-special'
restore_sleep_first_upsell_url = 'https://staging.zonia.com/restore-sleep-6-more-bottles'
restore_sleep_second_upsell_url = 'https://staging.zonia.com/rs-restore-life-6-discounted-bottles'
restore_sleep_third_upsell_url = 'https://staging.zonia.com/rs-restore-detox-6-discounted-bottles'
restore_sleep_fourth_upsell_url = 'https://staging.zonia.com/rs-trial'

restore_sleep_b2g3_start_url = 'https://staging.zonia.com/restore-sleep-3-free-bottles'
restore_sleep_b2g3_first_upsell_url = 'https://staging.zonia.com/restore-sleep-6-more-bottles-2'
restore_sleep_b2g3_second_upsell_url = 'https://staging.zonia.com/rs-restore-life-6-discounted-bottles-2'
restore_sleep_b2g3_third_upsell_url = 'https://staging.zonia.com/rs-restore-detox-6-discounted-bottles-2'
restore_sleep_b2g3_fourth_upsell_url = 'https://staging.zonia.com/rs-trial'

restore_gut_start_url = 'https://staging.zonia.com/restore-gut-special'
restore_gut_first_upsell_url = 'https://staging.zonia.com/restore-gut-6-more-bottles'
restore_gut_second_upsell_url = 'https://staging.zonia.com/rg-restore-detox-6-discounted-bottles'
restore_gut_third_upsell_url = 'https://staging.zonia.com/rg-restore-sleep-6-discounted-bottles'
restore_gut_fourth_upsell_url = 'https://staging.zonia.com/rg-trial'

restore_vision_start_url = 'https://staging.zonia.com/restore-vision-special'
restore_vision_first_upsell_url = 'https://staging.zonia.com/restore-vision-6-more-bottles'
restore_vision_second_upsell_url = 'https://staging.zonia.com/rg-restore-sleep-6-discounted-bottles'
restore_vision_third_upsell_url = 'https://staging.zonia.com/rg-restore-retox-6-discounted-bottles'
restore_vision_fourth_upsell_url = 'https://staging.zonia.com/rv-trial'

supplement_funnel_name = ''
supplement_funnel_email = ''
supplement_funnel_password = ''
supplement_funnel_bottles = ''
docuseries_address_will_appear = False
docuseries_address_already_filled = False
membership_added = False


test_cc_number = ''
test_cc_type = ''
test_cc_expiration_date = '0527'
test_cc_cvv = '123'
test_cc_zip = '1000'
card_index = 0
test_cards = [
            {"number": "4009348888881881", "type": "Visa"},
            {"number": "5555555555554444", "type": "MasterCard"},
            {"number": "378282246310005", "type": "American Express"},
            {"number": "36259600000004", "type": "Diners Club"},
            {"number": "6011000991300009", "type": "Discover"},
            {"number": "6221261111117766", "type": "UnionPay"},
            {"number": "3530111333300000", "type": "JCB"},
        ]

