opt_in_url = 'https://nishanranjitkar.com/portfolio/unbroken-opt-in/#form-target'
# opt_in_url = 'https://staging.zonia.com/beyond-the-brain/'
join_zonia_url = 'https://staging.zonia.com/bb-join-zonia'
sign_up_url = 'https://staging.zonia.com/bb-signup'
booster_upsale_url = 'https://staging.zonia.com/bb-booster-packages-monthly'
masterclass_url = 'https://staging.zonia.com/bb-mini-masterclass-series-platinum-package'
restore_detox_url = 'https://staging.zonia.com/bb-restore-detox-special'
restore_detox_upsell_url = 'https://staging.zonia.com/bb-rd-6-more-bottles'
restore_detox_downsell_url = 'https://staging.zonia.com/bb-rd-6-discounted-bottles'
restore_life_url = 'https://staging.zonia.com/bb-restore-life-special'
restore_life_upsell_url = 'https://staging.zonia.com/bb-rl-6-more-bottles'
restore_life_downsell_url = 'https://staging.zonia.com/bb-rl-6-discounted-bottles'
welcome_page_url = 'https://staging.zonia.com/welcome'

restore_sleep_start_url = 'https://staging.zonia.com/restore-sleep-3-free-bottles'
restore_sleep_first_upsell_url = 'https://staging.zonia.com/restore-sleep-6-more-bottles'
restore_sleep_second_upsell_url = 'https://zonia.com/rs-restore-life-6-discounted-bottles'
restore_sleep_third_upsell_url = 'https://zonia.com/rs-restore-detox-6-discounted-bottles'
restore_sleep_fourth_upsell_url = 'https://zonia.com/rs-trial'


test_cc_number = '4242424242424242'
test_cc_expiration_date = '05/27'
test_cc_cvv = '123'
test_cc_zip = '1000'

