# Opt-in page locators:
form_logo = "//*[starts-with(@class, 'form-logo')]"
register1_button = "//*[@class='btn btn-1']"
register2_button = "//div[starts-with(@class, 'section unbroken-opt-in-section-5')]//a[@class='btn btn-1 mb-3 mb-md-4']"
register3_button = "//div[starts-with(@class, 'section unbroken-opt-in-section-6')]//a[@class='btn btn-1 mb-3 mb-md-4']"
register4_button = "//div[starts-with(@class, 'section unbroken-opt-in-section-8')]//a[@class='btn btn-1 mb-3 mb-md-4']"
register5_button = "//div[starts-with(@class, 'section unbroken-opt-in-section-11')]//a[@class='btn btn-1 mb-3 mb-md-4']"
register6_button = "//div[starts-with(@class, 'section unbroken-opt-in-section-13')]//a[@class='btn btn-1 mb-3 mb-md-4']"
register7_button = "//div[starts-with(@class, 'section unbroken-opt-in-section-14')]//a[@class='btn btn-1 mb-3 mb-md-4']"
register8_button = "//div[starts-with(@class, 'section unbroken-opt-in-section-18')]//a[@class='btn btn-1 mb-3 mb-md-4']"
register9_button = "//div[starts-with(@class, 'section unbroken-opt-in-section-19')]//a[@class='btn btn-1 mb-3 mb-md-4']"
register10_button = "//div[starts-with(@class, 'section unbroken-opt-in-section-22')]//a[@class='btn btn-1 mb-3 mb-md-4']"
first_name_field = "//input[@id='first-name']"
email_field = "//input[@id='email']"
close_popup_button = "//div[@class='book-pop-up-form']//button[@aria-label='Close']"
register_button = "//div[@class='pop-up-register-form phone-parent-wrapper']//button[contains(text(), 'Register for free now')]"

# Join Zonia page locators:
join_button = "//a[@class='btn btn-1' and contains(text(), 'JOIN ZONIA NOW')]"

# Sign-Up page locators:
monthly_radio_button = "//input[@data-cycle='monthly_new']"
quarterly_radio_button = "//input[@data-cycle='quarterly']"
annually_radio_button = "//input[@data-cycle='yearly_new']"
signup_name_field = "//input[@id='form-name']"
signup_email_field = "//input[@id='form-email']"
signup_password_field = "//input[@id='form-password']"
signup_cc_number_iframe = "//iframe[@id='braintree-hosted-field-number']"
signup_cc_number_field = "//input[@id='credit-card-number']"
signup_cc_expiration_iframe = "//iframe[@id='braintree-hosted-field-expirationDate']"
signup_cc_expiration_field = "//input[@id='expiration']"
signup_cc_cvv_iframe = "//iframe[@id='braintree-hosted-field-cvv']"
signup_cc_cvv_field = "//input[@id='cvv']"
signup_cc_zip_iframe = "//iframe[@id='braintree-hosted-field-postalCode']"
signup_cc_zip_field = "//input[@id='postal-code']"
signup_activate_button = "//button[@class='activate-btn']"
