name: Nightly CR 1 Ep

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/device-test-runner.yaml
    with:
      report_name: nightly-cr-1ep
      device: desktop
      tags: '@cr_1ep'
      environment: staging
      report_scope: nightly
    secrets: inherit
