name: Nightly Face Scan

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/device-test-runner.yaml
    with:
      report_name: nightly-face-scan
      device: desktop
      tags: '@face_scan'
      environment: staging
      report_scope: nightly
    secrets: inherit
