name: Nightly Restore Detox and Sleep

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/device-test-runner.yaml
    with:
      report_name: nightly-restore-detox-life
      device: desktop
      tags: '@restore_detox,@restore_sleep'
      environment: staging
      report_scope: nightly
    secrets: inherit
