name: Run Tests 2

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.5

      - name: Run tests
        uses: cryptic-wizard/run-behave-tests@v0.4.0
        with:
          test-path: ./
          test-output-name: results.txt