name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run tests
        run: behave --tags @WIP --junit --junit-directory test-reports

      - name: Upload test reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test reports
          path: test-reports