name: Weekend Sunday iPad Landscape

on:
  schedule:
    - cron: '0 11 * * 0'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/device-test-runner.yaml
    with:
      report_name: weekend-sunday-ipad_landscape
      device: ipad_landscape
      tags: '@bb_evergreen,@nightly'
      environment: staging
      report_scope: mobile
    secrets: inherit
